### ISSUE TITLE
Does this work with AMS 1? 

### ISSUE THREAD

**Issue by tinker-tim** [viper4gh/CREST2-AMS2#2]
I'm looking for an accessible alternative to Live Racers given that's end of life, would this project be suitable to build on top of?

**Comment by viper4gh** [comment]
Unfortunately no.
AMS2 is based on the Madness Engine, where AMS1 is based on another engine.
CREST is only working for titles with the Madness Engine and still then there are different repos for every title, this one here works for AMS2 only. 
Further I am not the original developer of CREST, I only mantain it to keep it up-to-date if there are changes in the Shared Memory API.
That means I have not the know how to build the tool from scratch for a completely different API, sorry.
